steps:

- id: 'copy files'
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/PedroRyago/terraform-gcp', '/proj', 'cd proj/terraform-exemplo2']

- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - 'terraform init'

- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - 'terraform apply -auto-approve'

